name: turkey_rnaseq
channels:
  - conda-forge
  - bioconda
  - r
  - nodefaults
dependencies:
  - python
  - pysam
  - samtools
  - hisat2
  - gffcompare
  - stringtie
  - trim-galore
  - multiqc
  - r-base
  - r-tidyverse
  - r-devtools
  - r-glue
  - r-patchwork
  - r-ggsci
  - r-english
  - r-tinytex
  - r-pheatmap
  - r-officedown
  - r-bookdown
  - r-ggtext
  - r-flextable
  - r-ggVennDiagram
  - r-ggvenn
  - bioconductor-deseq2
  - bioconductor-edger
  - bioconductor-biocinstaller
  - bioconductor-GenomicRanges
  - bioconductor-genefilter
  - bioconductor-GenomicAlignments
  - bioconductor-apeglm
  - bioconductor-rtracklayer
  - bioconductor-enrichplot
  - bioconductor-pathview
  - bioconductor-biomaRt
  - r-gprofiler2
  - r-plyr
  - r-dbplyr
  - r-msigdbr
  - r-ggplotify
  - snakemake
  - graphviz
  - igv
  - igvtools
